AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon GuardDuty for threat detection

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  Environment:
    Type: String
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ----------------------------------------------------------------------------
  # GuardDuty Detector
  # ----------------------------------------------------------------------------
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: FIFTEEN_MINUTES
      DataSources:
        S3Logs:
          Enable: true
        Kubernetes:
          AuditLogs:
            Enable: false  # ECS環境のため無効化
        MalwareProtection:
          ScanEc2InstanceWithFindings:
            EbsVolumes:
              Enable: false  # Fargateのため無効化
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-guardduty
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # SNS Topic for GuardDuty Findings
  # ----------------------------------------------------------------------------
  GuardDutyFindingsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-guardduty-findings
      DisplayName: GuardDuty Findings
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-guardduty-findings
        - Key: Environment
          Value: !Ref Environment

  GuardDutyFindingsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref GuardDutyFindingsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowGuardDutyPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref GuardDutyFindingsTopic

  # ----------------------------------------------------------------------------
  # EventBridge Rule for High/Medium Severity Findings
  # ----------------------------------------------------------------------------
  HighSeverityFindingsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-guardduty-high-findings
      Description: Alert on high and medium severity GuardDuty findings
      State: ENABLED
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
        detail:
          severity:
            - 7  # High
            - 7.0
            - 7.1
            - 7.2
            - 7.3
            - 7.4
            - 7.5
            - 7.6
            - 7.7
            - 7.8
            - 7.9
            - 8
            - 8.0
            - 8.1
            - 8.2
            - 8.3
            - 8.4
            - 8.5
            - 8.6
            - 8.7
            - 8.8
            - 8.9
      Targets:
        - Arn: !Ref GuardDutyFindingsTopic
          Id: GuardDutyFindingsSNS

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  GuardDutyDetectorId:
    Value: !Ref GuardDutyDetector
    Description: GuardDuty Detector ID
    Export:
      Name: !Sub ${ProjectName}-${Environment}-GuardDutyDetectorId

  GuardDutyFindingsTopicArn:
    Value: !Ref GuardDutyFindingsTopic
    Description: SNS Topic ARN for GuardDuty Findings
    Export:
      Name: !Sub ${ProjectName}-${Environment}-GuardDutyFindingsTopicArn
