AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Security Hub for centralized security management

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  Environment:
    Type: String
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ----------------------------------------------------------------------------
  # Security Hub
  # ----------------------------------------------------------------------------
  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties:
      ControlFindingGenerator: SECURITY_CONTROL
      EnableDefaultStandards: true
      Tags:
        Name: !Sub ${ProjectName}-${Environment}-security-hub
        Environment: !Ref Environment

  # ----------------------------------------------------------------------------
  # Enable AWS Foundational Security Best Practices
  # ----------------------------------------------------------------------------
  FoundationalSecurityStandard:
    Type: AWS::SecurityHub::Standard
    DependsOn: SecurityHub
    Properties:
      StandardsArn: !Sub arn:aws:securityhub:${AWS::Region}::standards/aws-foundational-security-best-practices/v/1.0.0
      DisabledStandardsControls: []

  # ----------------------------------------------------------------------------
  # Enable CIS AWS Foundations Benchmark
  # ----------------------------------------------------------------------------
  CISStandard:
    Type: AWS::SecurityHub::Standard
    DependsOn: SecurityHub
    Properties:
      StandardsArn: !Sub arn:aws:securityhub:${AWS::Region}::standards/cis-aws-foundations-benchmark/v/1.4.0
      DisabledStandardsControls: []

  # ----------------------------------------------------------------------------
  # SNS Topic for Security Findings
  # ----------------------------------------------------------------------------
  SecurityFindingsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-security-findings
      DisplayName: Security Hub Findings
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-security-findings
        - Key: Environment
          Value: !Ref Environment

  SecurityFindingsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SecurityFindingsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSecurityHubPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SecurityFindingsTopic

  # ----------------------------------------------------------------------------
  # EventBridge Rule for Critical/High Findings
  # ----------------------------------------------------------------------------
  CriticalFindingsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-security-critical-findings
      Description: Alert on critical and high severity Security Hub findings
      State: ENABLED
      EventPattern:
        source:
          - aws.securityhub
        detail-type:
          - Security Hub Findings - Imported
        detail:
          findings:
            Severity:
              Label:
                - CRITICAL
                - HIGH
            Workflow:
              Status:
                - NEW
      Targets:
        - Arn: !Ref SecurityFindingsTopic
          Id: SecurityFindingsSNS

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  SecurityHubArn:
    Value: !GetAtt SecurityHub.Arn
    Description: Security Hub ARN
    Export:
      Name: !Sub ${ProjectName}-${Environment}-SecurityHubArn

  SecurityFindingsTopicArn:
    Value: !Ref SecurityFindingsTopic
    Description: SNS Topic ARN for Security Findings
    Export:
      Name: !Sub ${ProjectName}-${Environment}-SecurityFindingsTopicArn
