AWSTemplateFormatVersion: '2010-09-09'
Description: 'SNS Topic for Alarm Notifications'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Description: Project name

  Environment:
    Type: String
    Description: Environment name

  AlertEmail:
    Type: String
    Description: Email address for alarm notifications

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # --------------------------------------------------------------------------
  # SNS Topic
  # --------------------------------------------------------------------------
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-alarms
      DisplayName: !Sub ${ProjectName} ${Environment} Alarms
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-alarms
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # --------------------------------------------------------------------------
  # SNS Subscription (Email)
  # --------------------------------------------------------------------------
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref AlertEmail

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  SNSTopicArn:
    Description: SNS Topic ARN
    Value: !Ref SNSTopic
