AWSTemplateFormatVersion: '2010-09-09'
Description: 'EventBridge Rules for Scheduled Batch Tasks'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  MonthlyBatchCron:
    Type: String
    Default: 'cron(0 17 L * ? *)'
    Description: Cron expression for monthly batch (UTC, default is last day of month 17:00 UTC = 2:00 JST next day)

  YearlyBatchCron:
    Type: String
    Default: 'cron(0 17 31 3 ? *)'
    Description: Cron expression for yearly batch (UTC, default is March 31 17:00 UTC = April 1 2:00 JST)

Resources:
  # ------------------------------------------------------------
  # IAM Role for EventBridge to invoke ECS Task
  # ------------------------------------------------------------
  EventBridgeECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${Environment}-eventbridge-ecs-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceEventsRole
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-eventbridge-ecs-role
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: EventBridge to ECS Task Execution Role
        - Key: ManagedBy
          Value: CloudFormation

  # ------------------------------------------------------------
  # EventBridge Rule: Monthly Batch (月次集計)
  # ------------------------------------------------------------
  MonthlyBatchRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-monthly-batch
      Description: Monthly aggregation batch (last day of month 17:00 UTC = 2:00 JST next day)
      ScheduleExpression: !Ref MonthlyBatchCron
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-ecs-cluster-arn
          RoleArn: !GetAtt EventBridgeECSTaskRole.Arn
          Id: monthly-batch-target
          EcsParameters:
            TaskDefinitionArn: !ImportValue
              Fn::Sub: ${ProjectName}-${Environment}-batch-task-def
            TaskCount: 1
            LaunchType: FARGATE
            PlatformVersion: LATEST
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                Subnets:
                  - !ImportValue
                      Fn::Sub: ${ProjectName}-${Environment}-private-subnet-1-id
                  - !ImportValue
                      Fn::Sub: ${ProjectName}-${Environment}-private-subnet-2-id
                SecurityGroups:
                  - !ImportValue
                      Fn::Sub: ${ProjectName}-${Environment}-ecs-batch-sg-id
          Input: !Sub |
            {
              "batch_type": "monthly",
              "environment": "${Environment}"
            }

  # ------------------------------------------------------------
  # EventBridge Rule: Yearly Batch (年次集計)
  # ------------------------------------------------------------
  YearlyBatchRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-yearly-batch
      Description: Yearly aggregation batch (March 31 17:00 UTC = April 1 2:00 JST)
      ScheduleExpression: !Ref YearlyBatchCron
      State: ENABLED
      Targets:
        - Arn: !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-ecs-cluster-arn
          RoleArn: !GetAtt EventBridgeECSTaskRole.Arn
          Id: yearly-batch-target
          EcsParameters:
            TaskDefinitionArn: !ImportValue
              Fn::Sub: ${ProjectName}-${Environment}-batch-task-def
            TaskCount: 1
            LaunchType: FARGATE
            PlatformVersion: LATEST
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                Subnets:
                  - !ImportValue
                      Fn::Sub: ${ProjectName}-${Environment}-private-subnet-1-id
                  - !ImportValue
                      Fn::Sub: ${ProjectName}-${Environment}-private-subnet-2-id
                SecurityGroups:
                  - !ImportValue
                      Fn::Sub: ${ProjectName}-${Environment}-ecs-batch-sg-id
          Input: !Sub |
            {
              "batch_type": "yearly",
              "environment": "${Environment}"
            }

Outputs:
  MonthlyBatchRuleName:
    Description: Monthly Batch EventBridge Rule Name
    Value: !Ref MonthlyBatchRule
    Export:
      Name: !Sub ${ProjectName}-${Environment}-monthly-batch-rule-name

  MonthlyBatchRuleArn:
    Description: Monthly Batch EventBridge Rule ARN
    Value: !GetAtt MonthlyBatchRule.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-monthly-batch-rule-arn

  YearlyBatchRuleName:
    Description: Yearly Batch EventBridge Rule Name
    Value: !Ref YearlyBatchRule
    Export:
      Name: !Sub ${ProjectName}-${Environment}-yearly-batch-rule-name

  YearlyBatchRuleArn:
    Description: Yearly Batch EventBridge Rule ARN
    Value: !GetAtt YearlyBatchRule.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-yearly-batch-rule-arn

  EventBridgeECSTaskRoleArn:
    Description: EventBridge ECS Task Execution Role ARN
    Value: !GetAtt EventBridgeECSTaskRole.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-eventbridge-ecs-role-arn
