AWSTemplateFormatVersion: '2010-09-09'
Description: 'Target Groups for ALB'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Description: Project name

  Environment:
    Type: String
    Description: Environment name

  VpcId:
    Type: String
    Description: VPC ID

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # --------------------------------------------------------------------------
  # Target Group (Staff API)
  # --------------------------------------------------------------------------
  StaffApiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-staff-tg
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckEnabled: true
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      DeregistrationDelay: 300
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-staff-tg
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # --------------------------------------------------------------------------
  # Target Group (Vendor API)
  # --------------------------------------------------------------------------
  VendorApiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-vendor-tg
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckEnabled: true
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      DeregistrationDelay: 300
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-vendor-tg
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  StaffApiTargetGroupArn:
    Description: Staff API Target Group ARN
    Value: !Ref StaffApiTargetGroup

  VendorApiTargetGroupArn:
    Description: Vendor API Target Group ARN
    Value: !Ref VendorApiTargetGroup
