AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Alarms for RDS PostgreSQL'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  CPUUtilizationThreshold:
    Type: Number
    Default: 80
    Description: Threshold for RDS CPU utilization (%)

  FreeStorageSpaceThreshold:
    Type: Number
    Default: 10737418240
    Description: Threshold for RDS Free Storage Space (bytes, default 10GB)

  DatabaseConnectionsThreshold:
    Type: Number
    Default: 80
    Description: Threshold for RDS Database Connections (count)

Resources:
  # ------------------------------------------------------------
  # RDS Alarm: High CPU Utilization
  # ------------------------------------------------------------
  RDSCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-high-cpu
      AlarmDescription: RDS PostgreSQL CPU utilization is high
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: !Ref CPUUtilizationThreshold
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${ProjectName}-${Environment}-postgres
      AlarmActions:
        - !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-alert-topic-arn
      TreatMissingData: notBreaching

  # ------------------------------------------------------------
  # RDS Alarm: Low Free Storage Space
  # ------------------------------------------------------------
  RDSStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-low-storage
      AlarmDescription: RDS PostgreSQL free storage space is low
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref FreeStorageSpaceThreshold
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${ProjectName}-${Environment}-postgres
      AlarmActions:
        - !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-alert-topic-arn
      TreatMissingData: notBreaching

  # ------------------------------------------------------------
  # RDS Alarm: High Database Connections
  # ------------------------------------------------------------
  RDSConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-high-connections
      AlarmDescription: RDS PostgreSQL database connections are high
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: !Ref DatabaseConnectionsThreshold
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${ProjectName}-${Environment}-postgres
      AlarmActions:
        - !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-alert-topic-arn
      TreatMissingData: notBreaching

  # ------------------------------------------------------------
  # RDS Alarm: Read Latency
  # ------------------------------------------------------------
  RDSReadLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-high-read-latency
      AlarmDescription: RDS PostgreSQL read latency is high
      MetricName: ReadLatency
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${ProjectName}-${Environment}-postgres
      AlarmActions:
        - !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-alert-topic-arn
      TreatMissingData: notBreaching

  # ------------------------------------------------------------
  # RDS Alarm: Write Latency
  # ------------------------------------------------------------
  RDSWriteLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-high-write-latency
      AlarmDescription: RDS PostgreSQL write latency is high
      MetricName: WriteLatency
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 0.1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${ProjectName}-${Environment}-postgres
      AlarmActions:
        - !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-alert-topic-arn
      TreatMissingData: notBreaching

  # ------------------------------------------------------------
  # RDS Alarm: Replica Lag (Multi-AZ only)
  # ------------------------------------------------------------
  RDSReplicaLagAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-replica-lag
      AlarmDescription: RDS PostgreSQL replica lag is high
      MetricName: ReplicaLag
      Namespace: AWS/RDS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 30000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${ProjectName}-${Environment}-postgres
      AlarmActions:
        - !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-alert-topic-arn
      TreatMissingData: notBreaching

  # ------------------------------------------------------------
  # RDS Alarm: Freeable Memory
  # ------------------------------------------------------------
  RDSFreeableMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ProjectName}-${Environment}-rds-low-memory
      AlarmDescription: RDS PostgreSQL freeable memory is low
      MetricName: FreeableMemory
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 268435456
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Sub ${ProjectName}-${Environment}-postgres
      AlarmActions:
        - !ImportValue
            Fn::Sub: ${ProjectName}-${Environment}-alert-topic-arn
      TreatMissingData: notBreaching

Outputs:
  RDSCPUAlarmName:
    Description: RDS High CPU Alarm Name
    Value: !Ref RDSCPUAlarm
    Export:
      Name: !Sub ${ProjectName}-${Environment}-rds-cpu-alarm-name

  RDSStorageAlarmName:
    Description: RDS Low Storage Alarm Name
    Value: !Ref RDSStorageAlarm
    Export:
      Name: !Sub ${ProjectName}-${Environment}-rds-storage-alarm-name

  RDSConnectionsAlarmName:
    Description: RDS High Connections Alarm Name
    Value: !Ref RDSConnectionsAlarm
    Export:
      Name: !Sub ${ProjectName}-${Environment}-rds-connections-alarm-name
