AWSTemplateFormatVersion: '2010-09-09'
Description: 'KMS Keys - Additional Customer Managed Keys (CloudTrail, S3)'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

Resources:
  # ------------------------------------------------------------
  # KMS Key: CloudTrail Logs Encryption
  # ------------------------------------------------------------
  CloudTrailKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub KMS Key for CloudTrail Logs - ${Environment}
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          # Root account full access
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'

          # CloudTrail service permission
          - Sid: Allow CloudTrail to encrypt logs
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - kms:GenerateDataKey
              - kms:DecryptDataKey
            Resource: '*'
            Condition:
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*

          # CloudWatch Logs service permission
          - Sid: Allow CloudWatch Logs
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:CreateGrant
              - kms:DescribeKey
            Resource: '*'
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
      EnableKeyRotation: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-cloudtrail-key
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: CloudTrail Logs Encryption
        - Key: ManagedBy
          Value: CloudFormation

  CloudTrailKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${ProjectName}-${Environment}-cloudtrail
      TargetKeyId: !Ref CloudTrailKMSKey

  # ------------------------------------------------------------
  # KMS Key: S3 Bucket Encryption (Frontend SPAs)
  # ------------------------------------------------------------
  S3KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub KMS Key for S3 Buckets - ${Environment}
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          # Root account full access
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'

          # S3 service permission
          - Sid: Allow S3 to use the key
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'

          # CloudFront service permission (for OAC)
          - Sid: Allow CloudFront to use the key
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/*

          # ECS Task Role permission (for uploading reports)
          - Sid: Allow ECS Tasks to use the key
            Effect: Allow
            Principal:
              AWS: !ImportValue
                Fn::Sub: ${ProjectName}-${Environment}-ecs-task-role-arn
            Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:DescribeKey
            Resource: '*'
      EnableKeyRotation: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-s3-key
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: S3 Bucket Encryption
        - Key: ManagedBy
          Value: CloudFormation

  S3KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${ProjectName}-${Environment}-s3
      TargetKeyId: !Ref S3KMSKey

Outputs:
  CloudTrailKMSKeyId:
    Description: CloudTrail KMS Key ID
    Value: !Ref CloudTrailKMSKey
    Export:
      Name: !Sub ${ProjectName}-${Environment}-cloudtrail-kms-key-id

  CloudTrailKMSKeyArn:
    Description: CloudTrail KMS Key ARN
    Value: !GetAtt CloudTrailKMSKey.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-cloudtrail-kms-key-arn

  S3KMSKeyId:
    Description: S3 KMS Key ID
    Value: !Ref S3KMSKey
    Export:
      Name: !Sub ${ProjectName}-${Environment}-s3-kms-key-id

  S3KMSKeyArn:
    Description: S3 KMS Key ARN
    Value: !GetAtt S3KMSKey.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-s3-kms-key-arn
