AWSTemplateFormatVersion: '2010-09-09'
Description: 'DB Parameter Group for RDS PostgreSQL'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Description: Project name

  Environment:
    Type: String
    Description: Environment name

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # --------------------------------------------------------------------------
  # DB Parameter Group
  # --------------------------------------------------------------------------
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: !Sub ${ProjectName}-${Environment}-pg14-params
      Description: !Sub Custom parameter group for PostgreSQL 14 (${ProjectName} ${Environment})
      Family: postgres14
      Parameters:
        max_connections: '200'
        shared_buffers: '{DBInstanceClassMemory/16384}'
        effective_cache_size: '{DBInstanceClassMemory*3/4}'
        work_mem: '16384'
        maintenance_work_mem: '262144'
        log_statement: 'all'
        log_min_duration_statement: '1000'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-pg14-params
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  DBParameterGroupName:
    Description: DB Parameter Group Name
    Value: !Ref DBParameterGroup
