AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito User Pools for Staff and Vendor Authentication'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

Resources:
  # ------------------------------------------------------------
  # Cognito User Pool: Staff (職員用)
  # ------------------------------------------------------------
  StaffUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${ProjectName}-${Environment}-staff-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: department
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: employee_id
          AttributeDataType: String
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      UserPoolTags:
        Name: !Sub ${ProjectName}-${Environment}-staff-pool
        Environment: !Ref Environment
        Purpose: Staff User Pool
        ManagedBy: CloudFormation

  # ------------------------------------------------------------
  # Cognito User Pool Domain: Staff
  # ------------------------------------------------------------
  StaffUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${ProjectName}-${Environment}-staff
      UserPoolId: !Ref StaffUserPool

  # ------------------------------------------------------------
  # Cognito User Pool: Vendor (事業者用)
  # ------------------------------------------------------------
  VendorUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${ProjectName}-${Environment}-vendor-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: company_id
          AttributeDataType: String
          Required: false
          Mutable: false
        - Name: company_name
          AttributeDataType: String
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      UserPoolTags:
        Name: !Sub ${ProjectName}-${Environment}-vendor-pool
        Environment: !Ref Environment
        Purpose: Vendor User Pool
        ManagedBy: CloudFormation

  # ------------------------------------------------------------
  # Cognito User Pool Domain: Vendor
  # ------------------------------------------------------------
  VendorUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${ProjectName}-${Environment}-vendor
      UserPoolId: !Ref VendorUserPool

Outputs:
  StaffUserPoolId:
    Description: Staff Cognito User Pool ID
    Value: !Ref StaffUserPool
    Export:
      Name: !Sub ${ProjectName}-${Environment}-staff-user-pool-id

  StaffUserPoolArn:
    Description: Staff Cognito User Pool ARN
    Value: !GetAtt StaffUserPool.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-staff-user-pool-arn

  StaffUserPoolDomain:
    Description: Staff Cognito User Pool Domain
    Value: !Ref StaffUserPoolDomain
    Export:
      Name: !Sub ${ProjectName}-${Environment}-staff-user-pool-domain

  VendorUserPoolId:
    Description: Vendor Cognito User Pool ID
    Value: !Ref VendorUserPool
    Export:
      Name: !Sub ${ProjectName}-${Environment}-vendor-user-pool-id

  VendorUserPoolArn:
    Description: Vendor Cognito User Pool ARN
    Value: !GetAtt VendorUserPool.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-vendor-user-pool-arn

  VendorUserPoolDomain:
    Description: Vendor Cognito User Pool Domain
    Value: !Ref VendorUserPoolDomain
    Export:
      Name: !Sub ${ProjectName}-${Environment}-vendor-user-pool-domain
