AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito User Pool Clients for Staff and Vendor SPAs'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  StaffCallbackURL:
    Type: String
    Default: 'https://localhost:3000/callback'
    Description: Staff SPA Callback URL

  VendorCallbackURL:
    Type: String
    Default: 'https://localhost:4000/callback'
    Description: Vendor SPA Callback URL

Resources:
  # ------------------------------------------------------------
  # Cognito User Pool Client: Staff SPA
  # ------------------------------------------------------------
  StaffUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${ProjectName}-${Environment}-staff-client
      UserPoolId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-staff-user-pool-id
      GenerateSecret: false
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      ReadAttributes:
        - email
        - email_verified
        - custom:department
        - custom:employee_id
      WriteAttributes:
        - email
        - custom:department
        - custom:employee_id
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Ref StaffCallbackURL
      LogoutURLs:
        - !Ref StaffCallbackURL
      SupportedIdentityProviders:
        - COGNITO

  # ------------------------------------------------------------
  # Cognito User Pool Client: Vendor SPA
  # ------------------------------------------------------------
  VendorUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${ProjectName}-${Environment}-vendor-client
      UserPoolId: !ImportValue
        Fn::Sub: ${ProjectName}-${Environment}-vendor-user-pool-id
      GenerateSecret: false
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      ReadAttributes:
        - email
        - email_verified
        - custom:company_id
        - custom:company_name
      WriteAttributes:
        - email
        - custom:company_name
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Ref VendorCallbackURL
      LogoutURLs:
        - !Ref VendorCallbackURL
      SupportedIdentityProviders:
        - COGNITO

Outputs:
  StaffUserPoolClientId:
    Description: Staff Cognito User Pool Client ID
    Value: !Ref StaffUserPoolClient
    Export:
      Name: !Sub ${ProjectName}-${Environment}-staff-user-pool-client-id

  VendorUserPoolClientId:
    Description: Vendor Cognito User Pool Client ID
    Value: !Ref VendorUserPoolClient
    Export:
      Name: !Sub ${ProjectName}-${Environment}-vendor-user-pool-client-id
