AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for Frontend Static Files'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Description: Project name

  Environment:
    Type: String
    Description: Environment name

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # --------------------------------------------------------------------------
  # S3 Bucket (Frontend)
  # --------------------------------------------------------------------------
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-${Environment}-frontend-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-frontend
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # --------------------------------------------------------------------------
  # Bucket Policy (CloudFront OAI access only)
  # --------------------------------------------------------------------------
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontOAI
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  # --------------------------------------------------------------------------
  # CloudFront Origin Access Identity
  # --------------------------------------------------------------------------
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub OAI for ${ProjectName}-${Environment}-frontend

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  FrontendBucketName:
    Description: Frontend S3 Bucket Name
    Value: !Ref FrontendBucket

  FrontendBucketArn:
    Description: Frontend S3 Bucket ARN
    Value: !GetAtt FrontendBucket.Arn

  FrontendBucketDomainName:
    Description: Frontend S3 Bucket Domain Name
    Value: !GetAtt FrontendBucket.RegionalDomainName

  CloudFrontOAI:
    Description: CloudFront Origin Access Identity
    Value: !Ref CloudFrontOAI
