AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC and Internet Gateway'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Description: Project name

  Environment:
    Type: String
    Description: Environment name

  VpcCidr:
    Type: String
    Description: VPC CIDR block

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # --------------------------------------------------------------------------
  # VPC
  # --------------------------------------------------------------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-vpc
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # --------------------------------------------------------------------------
  # Internet Gateway
  # --------------------------------------------------------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-igw
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC

  VpcCidr:
    Description: VPC CIDR
    Value: !GetAtt VPC.CidrBlock

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
