AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition for Batch Processing

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  BatchTaskCpu:
    Type: String
    Description: Batch Task CPU
    Default: '2048'

  BatchTaskMemory:
    Type: String
    Description: Batch Task Memory
    Default: '4096'

  ECSTaskExecutionRoleArn:
    Type: String
    Description: ECS Task Execution Role ARN

  ECSTaskRoleArn:
    Type: String
    Description: ECS Task Role ARN

  BatchLogGroupName:
    Type: String
    Description: CloudWatch Log Group Name for Batch

  DBSecretArn:
    Type: String
    Description: DB Secret ARN from Secrets Manager

Resources:
  BatchTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-${Environment}-batch
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref BatchTaskCpu
      Memory: !Ref BatchTaskMemory
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
      TaskRoleArn: !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: batch
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-batch:latest
          Essential: true
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: BATCH_TYPE
              Value: monthly_report
            - Name: LOG_LEVEL
              Value: info
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: !Sub ${DBSecretArn}:DATABASE_URL::
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BatchLogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-batch-task
        - Key: Environment
          Value: !Ref Environment

Outputs:
  BatchTaskDefinitionArn:
    Description: Batch Task Definition ARN
    Value: !Ref BatchTaskDefinition
    Export:
      Name: !Sub ${ProjectName}-${Environment}-BatchTaskDefArn
