AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition for Staff API

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  ECSTaskCpu:
    Type: String
    Description: Task CPU (256, 512, 1024, 2048, 4096)
    Default: '512'

  ECSTaskMemory:
    Type: String
    Description: Task Memory (512, 1024, 2048, 4096, 8192)
    Default: '1024'

  ECSTaskExecutionRoleArn:
    Type: String
    Description: ECS Task Execution Role ARN

  ECSTaskRoleArn:
    Type: String
    Description: ECS Task Role ARN

  StaffAPILogGroupName:
    Type: String
    Description: CloudWatch Log Group Name for Staff API

  DBSecretArn:
    Type: String
    Description: DB Secret ARN from Secrets Manager

Resources:
  StaffAPITaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-${Environment}-staff-api
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref ECSTaskCpu
      Memory: !Ref ECSTaskMemory
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
      TaskRoleArn: !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: staff-api
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-staff-api:latest
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: PORT
              Value: '3000'
            - Name: LOG_LEVEL
              Value: info
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: !Sub ${DBSecretArn}:DATABASE_URL::
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref StaffAPILogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3000/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-staff-api-task
        - Key: Environment
          Value: !Ref Environment

Outputs:
  StaffAPITaskDefinitionArn:
    Description: Staff API Task Definition ARN
    Value: !Ref StaffAPITaskDefinition
    Export:
      Name: !Sub ${ProjectName}-${Environment}-StaffAPITaskDefArn
