AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL 14 Instance

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  DBSubnetGroupName:
    Type: String
    Description: DB Subnet Group Name

  DBParameterGroupName:
    Type: String
    Description: DB Parameter Group Name

  DBOptionGroupName:
    Type: String
    Description: DB Option Group Name

  RDSSecurityGroupId:
    Type: String
    Description: RDS Security Group ID

  DBInstanceClass:
    Type: String
    Description: DB Instance Class
    Default: db.t4g.micro

  DBAllocatedStorage:
    Type: Number
    Description: Allocated Storage (GB)
    Default: 20

  DBMultiAZ:
    Type: String
    Description: Enable Multi-AZ
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  DBBackupRetentionPeriod:
    Type: Number
    Description: Backup Retention Period (days)
    Default: 7

  DBMasterUsername:
    Type: String
    Description: Master Username
    Default: postgres
    NoEcho: false

  # DBMasterPassword は Secrets Manager から取得するため、ここではダミー
  # 実運用では Secrets Manager Rotation を使用

Resources:
  # ==============================================================================
  # KMS Key for RDS Encryption
  # ==============================================================================
  DBEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub KMS key for RDS encryption (${ProjectName}-${Environment})
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow RDS to use the key
            Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:CreateGrant
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-rds-key
        - Key: Environment
          Value: !Ref Environment

  DBEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${ProjectName}-${Environment}-rds
      TargetKeyId: !Ref DBEncryptionKey

  # ==============================================================================
  # DB Instance
  # ==============================================================================
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-${Environment}-db
      DBName: facility
      Engine: postgres
      EngineVersion: '14.9'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      KmsKeyId: !Ref DBEncryptionKey
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroupName
      DBParameterGroupName: !Ref DBParameterGroupName
      OptionGroupName: !Ref DBOptionGroupName
      VPCSecurityGroups:
        - !Ref RDSSecurityGroupId
      MultiAZ: !Ref DBMultiAZ
      PubliclyAccessible: false
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      PreferredBackupWindow: '17:00-18:00'  # 深夜2-3時 JST
      PreferredMaintenanceWindow: 'sun:18:00-sun:19:00'  # 日曜深夜3-4時 JST
      AutoMinorVersionUpgrade: !If [IsProd, true, false]
      EnableCloudwatchLogsExports:
        - postgresql
      DeletionProtection: !If [IsProd, true, false]
      CopyTagsToSnapshot: true
      EnablePerformanceInsights: !If [IsProd, true, false]
      PerformanceInsightsRetentionPeriod: !If [IsProd, 7, !Ref 'AWS::NoValue']
      PerformanceInsightsKMSKeyId: !If [IsProd, !Ref DBEncryptionKey, !Ref 'AWS::NoValue']
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db
        - Key: Environment
          Value: !Ref Environment

  # ==============================================================================
  # Secrets Manager for DB Credentials
  # ==============================================================================
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-db-secret
      Description: !Sub Database credentials for ${Environment}
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBMasterUsername}"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      KmsKeyId: !Ref DBEncryptionKey
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-secret
        - Key: Environment
          Value: !Ref Environment

  # Secrets Manager と RDS の関連付け
  SecretRDSAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref DBInstance
      TargetType: AWS::RDS::DBInstance

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Outputs:
  DBInstanceIdentifier:
    Description: DB Instance Identifier
    Value: !Ref DBInstance
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBInstanceId

  DBInstanceEndpoint:
    Description: DB Instance Endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBEndpoint

  DBInstancePort:
    Description: DB Instance Port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBPort

  DBSecretArn:
    Description: DB Secret ARN (Secrets Manager)
    Value: !Ref DBSecret
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBSecretArn

  DBEncryptionKeyId:
    Description: KMS Key ID for RDS Encryption
    Value: !Ref DBEncryptionKey
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBEncryptionKey
