AWSTemplateFormatVersion: '2010-09-09'
Description: RDS DB Subnet Group

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  DataSubnet1Id:
    Type: String
    Description: Data Subnet 1 ID

  DataSubnet2Id:
    Type: String
    Description: Data Subnet 2 ID

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${ProjectName}-${Environment}-db-subnet-group
      DBSubnetGroupDescription: DB Subnet Group for RDS PostgreSQL
      SubnetIds:
        - !Ref DataSubnet1Id
        - !Ref DataSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-db-subnet-group
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DBSubnetGroupName:
    Description: DB Subnet Group Name
    Value: !Ref DBSubnetGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBSubnetGroup
