AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack for Network Shared Account (Hub)

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
    Description: Environment name (Network Shared is production only)

  ProjectName:
    Type: String
    Default: facility
    Description: Project name for resource naming

  TemplatesBucketName:
    Type: String
    Default: facility-cloudformation-templates
    Description: S3 bucket name for nested templates

  EgressVpcCidr:
    Type: String
    Default: 10.255.0.0/16
    Description: CIDR for Egress VPC

  TransitGatewayAsn:
    Type: Number
    Default: 64512
    Description: BGP ASN for Transit Gateway (Private ASN range: 64512-65534)

  ClientVpnCidr:
    Type: String
    Default: 172.16.0.0/16
    Description: CIDR for Client VPN (must not overlap with any VPC)

# ==============================================================================
# Resources - Nested Stacks
# ==============================================================================
Resources:
  # ----------------------------------------------------------------------------
  # Network Layer
  # ----------------------------------------------------------------------------
  TransitGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/network/transit-gateway.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        TransitGatewayAsn: !Ref TransitGatewayAsn
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-transit-gateway-stack
        - Key: Environment
          Value: !Ref Environment

  EgressVpcStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: TransitGatewayStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/network/egress-vpc.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcCidr: !Ref EgressVpcCidr
        TransitGatewayId: !GetAtt TransitGatewayStack.Outputs.TransitGatewayId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-egress-vpc-stack
        - Key: Environment
          Value: !Ref Environment

  NatGatewaysStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EgressVpcStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/network/nat-gateways.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt EgressVpcStack.Outputs.VpcId
        PublicSubnetAZa: !GetAtt EgressVpcStack.Outputs.PublicSubnetAZa
        PublicSubnetAZc: !GetAtt EgressVpcStack.Outputs.PublicSubnetAZc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-nat-gateways-stack
        - Key: Environment
          Value: !Ref Environment

  NetworkFirewallStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: EgressVpcStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/network/network-firewall.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt EgressVpcStack.Outputs.VpcId
        FirewallSubnetAZa: !GetAtt EgressVpcStack.Outputs.FirewallSubnetAZa
        FirewallSubnetAZc: !GetAtt EgressVpcStack.Outputs.FirewallSubnetAZc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-network-firewall-stack
        - Key: Environment
          Value: !Ref Environment

  ClientVpnStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: TransitGatewayStack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/network/client-vpn.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        ClientVpnCidr: !Ref ClientVpnCidr
        TransitGatewayId: !GetAtt TransitGatewayStack.Outputs.TransitGatewayId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-client-vpn-stack
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # Security Layer
  # ----------------------------------------------------------------------------
  SecurityHubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/security/security-hub.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-security-hub-stack
        - Key: Environment
          Value: !Ref Environment

  GuardDutyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/security/guardduty.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-guardduty-stack
        - Key: Environment
          Value: !Ref Environment

  ConfigStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/security/config.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-config-stack
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # Monitoring Layer
  # ----------------------------------------------------------------------------
  CloudTrailStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/monitoring/cloudtrail-org.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-cloudtrail-stack
        - Key: Environment
          Value: !Ref Environment

  CloudWatchLogsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.amazonaws.com/shared/nested/monitoring/cloudwatch-logs.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-cloudwatch-logs-stack
        - Key: Environment
          Value: !Ref Environment

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  TransitGatewayId:
    Value: !GetAtt TransitGatewayStack.Outputs.TransitGatewayId
    Export:
      Name: !Sub ${ProjectName}-${Environment}-TransitGatewayId
    Description: Transit Gateway ID for cross-account sharing

  EgressVpcId:
    Value: !GetAtt EgressVpcStack.Outputs.VpcId
    Export:
      Name: !Sub ${ProjectName}-${Environment}-EgressVpcId
    Description: Egress VPC ID

  NatGatewayAZa:
    Value: !GetAtt NatGatewaysStack.Outputs.NatGatewayAZa
    Description: NAT Gateway ID in AZ-a

  NatGatewayAZc:
    Value: !GetAtt NatGatewaysStack.Outputs.NatGatewayAZc
    Description: NAT Gateway ID in AZ-c

  NetworkFirewallArn:
    Value: !GetAtt NetworkFirewallStack.Outputs.FirewallArn
    Description: Network Firewall ARN

  ClientVpnEndpointId:
    Value: !GetAtt ClientVpnStack.Outputs.VpnEndpointId
    Description: Client VPN Endpoint ID
