AWSTemplateFormatVersion: '2010-09-09'
Description: NAT Gateways for Egress VPC

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  Environment:
    Type: String
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  VpcId:
    Type: String
    Description: Egress VPC ID

  PublicSubnetAZa:
    Type: String
    Description: Public Subnet in AZ-a

  PublicSubnetAZc:
    Type: String
    Description: Public Subnet in AZ-c

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ----------------------------------------------------------------------------
  # Elastic IPs for NAT Gateways
  # ----------------------------------------------------------------------------
  NatGatewayEIPAZa:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-nat-eip-az-a
        - Key: Environment
          Value: !Ref Environment

  NatGatewayEIPAZc:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-nat-eip-az-c
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # NAT Gateways
  # ----------------------------------------------------------------------------
  NatGatewayAZa:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIPAZa.AllocationId
      SubnetId: !Ref PublicSubnetAZa
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-nat-gw-az-a
        - Key: Environment
          Value: !Ref Environment

  NatGatewayAZc:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIPAZc.AllocationId
      SubnetId: !Ref PublicSubnetAZc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-nat-gw-az-c
        - Key: Environment
          Value: !Ref Environment

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  NatGatewayAZa:
    Value: !Ref NatGatewayAZa
    Description: NAT Gateway ID in AZ-a
    Export:
      Name: !Sub ${ProjectName}-${Environment}-NatGatewayAZa

  NatGatewayAZc:
    Value: !Ref NatGatewayAZc
    Description: NAT Gateway ID in AZ-c
    Export:
      Name: !Sub ${ProjectName}-${Environment}-NatGatewayAZc

  NatGatewayEIPAZa:
    Value: !Ref NatGatewayEIPAZa
    Description: NAT Gateway Elastic IP in AZ-a

  NatGatewayEIPAZc:
    Value: !Ref NatGatewayEIPAZc
    Description: NAT Gateway Elastic IP in AZ-c
