AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Network Firewall for egress traffic filtering

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  Environment:
    Type: String
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for resource naming

  VpcId:
    Type: String
    Description: Egress VPC ID

  FirewallSubnetAZa:
    Type: String
    Description: Firewall Subnet in AZ-a

  FirewallSubnetAZc:
    Type: String
    Description: Firewall Subnet in AZ-c

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ----------------------------------------------------------------------------
  # Firewall Rule Group - Domain Filtering
  # ----------------------------------------------------------------------------
  DomainAllowListRuleGroup:
    Type: AWS::NetworkFirewall::RuleGroup
    Properties:
      RuleGroupName: !Sub ${ProjectName}-${Environment}-domain-allow-list
      Type: STATEFUL
      Capacity: 100
      RuleGroup:
        RulesSource:
          RulesSourceList:
            TargetTypes:
              - HTTP_HOST
              - TLS_SNI
            Targets:
              # AWS Services
              - .amazonaws.com
              - .aws.amazon.com
              # Windows Update
              - .windowsupdate.microsoft.com
              - .update.microsoft.com
              - .download.windowsupdate.com
              # Docker Hub (Dev環境のみ、本番では削除推奨)
              - registry-1.docker.io
              - auth.docker.io
              - production.cloudflare.docker.com
              # GitHub (Dev環境のみ、本番では削除推奨)
              - github.com
              - api.github.com
              # npm / Node.js
              - registry.npmjs.org
              - nodejs.org
            GeneratedRulesType: ALLOWLIST
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-domain-allow-list
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # Firewall Rule Group - Port Filtering
  # ----------------------------------------------------------------------------
  PortFilterRuleGroup:
    Type: AWS::NetworkFirewall::RuleGroup
    Properties:
      RuleGroupName: !Sub ${ProjectName}-${Environment}-port-filter
      Type: STATEFUL
      Capacity: 50
      RuleGroup:
        RulesSource:
          StatefulRules:
            # Allow HTTPS
            - Action: PASS
              Header:
                Protocol: TCP
                Source: ANY
                SourcePort: ANY
                Direction: FORWARD
                Destination: ANY
                DestinationPort: '443'
              RuleOptions:
                - Keyword: sid
                  Settings:
                    - '1'
            # Allow HTTP (for redirects)
            - Action: PASS
              Header:
                Protocol: TCP
                Source: ANY
                SourcePort: ANY
                Direction: FORWARD
                Destination: ANY
                DestinationPort: '80'
              RuleOptions:
                - Keyword: sid
                  Settings:
                    - '2'
            # Drop SSH
            - Action: DROP
              Header:
                Protocol: TCP
                Source: ANY
                SourcePort: ANY
                Direction: FORWARD
                Destination: ANY
                DestinationPort: '22'
              RuleOptions:
                - Keyword: sid
                  Settings:
                    - '100'
            # Drop RDP
            - Action: DROP
              Header:
                Protocol: TCP
                Source: ANY
                SourcePort: ANY
                Direction: FORWARD
                Destination: ANY
                DestinationPort: '3389'
              RuleOptions:
                - Keyword: sid
                  Settings:
                    - '101'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-port-filter
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # Firewall Policy
  # ----------------------------------------------------------------------------
  FirewallPolicy:
    Type: AWS::NetworkFirewall::FirewallPolicy
    Properties:
      FirewallPolicyName: !Sub ${ProjectName}-${Environment}-egress-policy
      FirewallPolicy:
        StatelessDefaultActions:
          - aws:forward_to_sfe
        StatelessFragmentDefaultActions:
          - aws:forward_to_sfe
        StatefulRuleGroupReferences:
          - ResourceArn: !GetAtt DomainAllowListRuleGroup.RuleGroupArn
          - ResourceArn: !GetAtt PortFilterRuleGroup.RuleGroupArn
        StatefulDefaultActions:
          - aws:drop_established
          - aws:alert_established
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-egress-policy
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # Network Firewall
  # ----------------------------------------------------------------------------
  NetworkFirewall:
    Type: AWS::NetworkFirewall::Firewall
    Properties:
      FirewallName: !Sub ${ProjectName}-${Environment}-network-firewall
      FirewallPolicyArn: !GetAtt FirewallPolicy.FirewallPolicyArn
      VpcId: !Ref VpcId
      SubnetMappings:
        - SubnetId: !Ref FirewallSubnetAZa
        - SubnetId: !Ref FirewallSubnetAZc
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-network-firewall
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # CloudWatch Log Group for Firewall Logs
  # ----------------------------------------------------------------------------
  FirewallLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/network-firewall/${ProjectName}-${Environment}
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-firewall-logs
        - Key: Environment
          Value: !Ref Environment

  # ----------------------------------------------------------------------------
  # Firewall Logging Configuration
  # ----------------------------------------------------------------------------
  FirewallLoggingConfiguration:
    Type: AWS::NetworkFirewall::LoggingConfiguration
    Properties:
      FirewallArn: !Ref NetworkFirewall
      LoggingConfiguration:
        LogDestinationConfigs:
          - LogType: ALERT
            LogDestinationType: CloudWatchLogs
            LogDestination:
              logGroup: !Ref FirewallLogGroup
          - LogType: FLOW
            LogDestinationType: CloudWatchLogs
            LogDestination:
              logGroup: !Ref FirewallLogGroup

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  FirewallArn:
    Value: !Ref NetworkFirewall
    Description: Network Firewall ARN
    Export:
      Name: !Sub ${ProjectName}-${Environment}-NetworkFirewallArn

  FirewallId:
    Value: !GetAtt NetworkFirewall.FirewallId
    Description: Network Firewall ID

  FirewallEndpointAZa:
    Value: !Select [0, !GetAtt NetworkFirewall.EndpointIds]
    Description: Firewall Endpoint ID in AZ-a

  FirewallEndpointAZc:
    Value: !Select [1, !GetAtt NetworkFirewall.EndpointIds]
    Description: Firewall Endpoint ID in AZ-c

  FirewallLogGroupName:
    Value: !Ref FirewallLogGroup
    Description: CloudWatch Log Group for Firewall logs
