name: Deploy Shared Account (Network-Shared)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod

jobs:
  deploy:
    name: Deploy to Shared Account
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: AWS Credentials Not Configured
        run: |
          echo "========================================"
          echo "AWS CREDENTIALS ARE NOT CONFIGURED"
          echo "========================================"
          echo ""
          echo "This workflow is a template and cannot deploy to AWS without proper configuration."
          echo ""
          echo "To enable AWS deployment, you need to:"
          echo "1. Configure AWS OIDC in your AWS account"
          echo "2. Add the following secrets to GitHub repository:"
          echo "   - AWS_ROLE_ARN: ARN of the IAM role to assume"
          echo "   - AWS_REGION: AWS region (e.g., ap-northeast-1)"
          echo ""
          echo "See: docs/03_基本設計/09_CI_CD設計.md"
          echo ""
          exit 1
